sonar.projectKey=Frucek_simpletasks
sonar.organization=frucek
sonar.host.url=https://sonarcloud.io
sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/build/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info